/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        nbtc: {
          red: '#C00000',
          'red-dark': '#8B0000',
          'red-light': '#FFE5E5',
          navy: '#1A365D',
          gold: '#B8860B',
        },
        spectrum: {
          green: '#16A34A',
          gray: '#9CA3AF',
          red: '#DC2626',
        },
        imt: {
          inner: '#0D9488',
          mid: '#8B5CF6',
          outer: '#F472B6',
        }
      },
      fontFamily: {
        thai: ['Noto Sans Thai', 'Sarabun', 'sans-serif'],
        mono: ['Fira Code', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn var(--dur-normal) var(--ease-expo) both',
        'fade-in-up': 'fadeInUp var(--dur-normal) var(--ease-expo) both',
        'fade-in-down': 'fadeInDown var(--dur-normal) var(--ease-expo) both',
        'fade-in-left': 'fadeInLeft var(--dur-normal) var(--ease-expo) both',
        'fade-in-right': 'fadeInRight var(--dur-normal) var(--ease-expo) both',
        'scale-in': 'scaleIn var(--dur-normal) var(--ease-back) both',
        'slide-in-right': 'slideInRight var(--dur-slow) var(--ease-expo) both',
        'slide-out-right': 'slideOutRight var(--dur-slow) var(--ease-expo) both',
        'slide-in-up': 'slideInUp var(--dur-slow) var(--ease-expo) both',
        'press': 'pressScale var(--dur-micro) var(--ease-standard)',
        'number-bounce': 'numberBounce var(--dur-fast) var(--ease-back)',
        'border-glow': 'borderGlow var(--dur-slow) var(--ease-standard) infinite',
        'shimmer': 'shimmer 1.5s linear infinite',
        'pulse-ring': 'pulseRing var(--dur-pulse) var(--ease-smooth)',
        'shake': 'shakeError var(--dur-fast) var(--ease-standard)',
        'flash-green': 'flashHighlight var(--dur-slow) ease-out',
        'checkmark': 'checkmarkDraw var(--dur-slow) var(--ease-expo) forwards',
        'marker-drop': 'markerDrop var(--dur-sync) var(--ease-back) both',
        'radial-expand': 'radialExpand var(--dur-slow) var(--ease-expo) both',
        'line-draw': 'lineDraw var(--dur-slow) var(--ease-expo) forwards',
        'color-wave': 'colorWave 2s ease infinite',
        'pulse-border': 'pulseBorder 2s var(--ease-standard) infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeInUp: { '0%': { opacity: '0', transform: 'translateY(12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeInDown: { '0%': { opacity: '0', transform: 'translateY(-12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeInLeft: { '0%': { opacity: '0', transform: 'translateX(-12px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        fadeInRight: { '0%': { opacity: '0', transform: 'translateX(12px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.94)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        slideInRight: { '0%': { opacity: '0', transform: 'translateX(100%)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        slideOutRight: { '0%': { opacity: '1', transform: 'translateX(0)' }, '100%': { opacity: '0', transform: 'translateX(100%)' } },
        slideInUp: { '0%': { opacity: '0', transform: 'translateY(100%)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        pressScale: { '0%': { transform: 'scale(1)' }, '50%': { transform: 'scale(0.96)' }, '100%': { transform: 'scale(1)' } },
        rippleEffect: { '0%': { transform: 'scale(0)', opacity: '0.5' }, '100%': { transform: 'scale(4)', opacity: '0' } },
        borderGlow: { '0%,100%': { boxShadow: '0 0 0 0 rgba(192,0,0,0.3)' }, '50%': { boxShadow: '0 0 0 3px rgba(192,0,0,0.15)' } },
        numberBounce: { '0%': { transform: 'scale(1)' }, '25%': { transform: 'scale(1.04)' }, '50%': { transform: 'scale(0.98)' }, '100%': { transform: 'scale(1)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        pulseRing: { '0%': { boxShadow: '0 0 0 0 rgba(192,0,0,0.5)' }, '50%': { boxShadow: '0 0 0 12px rgba(192,0,0,0)' }, '100%': { boxShadow: '0 0 0 0 rgba(192,0,0,0)' } },
        checkmarkDraw: { '0%': { strokeDashoffset: '24' }, '40%': { strokeDashoffset: '24' }, '100%': { strokeDashoffset: '0' } },
        shakeError: { '0%,100%': { transform: 'translateX(0)' }, '20%': { transform: 'translateX(-4px)' }, '40%': { transform: 'translateX(4px)' }, '60%': { transform: 'translateX(-3px)' }, '80%': { transform: 'translateX(3px)' } },
        flashHighlight: { '0%': { backgroundColor: 'rgba(22,163,74,0.2)' }, '100%': { backgroundColor: 'transparent' } },
        markerDrop: { '0%': { opacity: '0', transform: 'translateY(-30px)' }, '60%': { opacity: '1', transform: 'translateY(3px)' }, '80%': { transform: 'translateY(-2px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        radialExpand: { '0%': { transform: 'scale(0)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        lineDraw: { '0%': { strokeDashoffset: '1000' }, '100%': { strokeDashoffset: '0' } },
        colorWave: { '0%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' }, '100%': { backgroundPosition: '0% 50%' } },
        pulseBorder: { '0%,100%': { borderColor: 'rgba(156,163,175,0.5)' }, '50%': { borderColor: 'rgba(234,179,8,0.8)' } },
      },
    },
  },
  plugins: [],
}
